// Generated by CoffeeScript 1.8.0
(function() {
  var ColorLuminance, avatar, dbReq, getRandomColor, loadProjectInto, projectContainer, projectList, projectTmpl, reqListener, signature, stuffContainer, stuffList, wololo;

  projectList = ["Kipos", "LudumPad", "ld48-29", "rule#34", "pzero", "enitor", "cellvorsum"];

  stuffList = ["subclass-error", "CanvasDye", "Eximo.js"];

  window.onload = function() {
    return jss.set('.ditto', {
      opacity: '1',
      transition: 'opacity 1s'
    });
  };

  avatar = document.getElementById('avatar');

  avatar.onclick = function() {
    return window.open('https://www.youtube.com/watch?v=SEOscGdcXZU', '_blank');
  };

  projectTmpl = document.getElementById('project-tmpl').innerHTML;

  Mustache.parse(projectTmpl);

  projectContainer = document.getElementById('projects');

  stuffContainer = document.getElementById('stuff');

  loadProjectInto = function(obj, container) {
    var node;
    node = document.createElement('div');
    node.className = 'project';
    node.innerHTML = Mustache.render(projectTmpl, obj);
    return container.appendChild(node);
  };

  reqListener = function() {
    var database;
    database = JSON.parse(this.responseText);
    projectList.forEach(function(projectName) {
      return loadProjectInto(database[projectName], projectContainer);
    });
    return stuffList.forEach(function(smthName) {
      return loadProjectInto(database[smthName], stuffContainer);
    });
  };

  dbReq = new XMLHttpRequest();

  dbReq.onload = reqListener;

  dbReq.open('get', '/js/projects.json', true);

  dbReq.send();

  getRandomColor = function() {
    var color, i, letters, _i;
    letters = '0123456789ABCDEF'.split('');
    color = '#';
    for (i = _i = 0; _i <= 5; i = ++_i) {
      color += letters[Math.floor(Math.random() * 16)];
    }
    return color;
  };

  ColorLuminance = function(hex, lum) {
    var c, i, rgb, _i;
    if (lum == null) {
      lum = 0;
    }
    hex = String(hex).replace(/[^0-9a-f]/gi, '');
    if (hex.length < 6) {
      hex = hex[0] + hex[0] + hex[1] + hex[1] + hex[2] + hex[2];
    }
    rgb = '#';
    for (i = _i = 0; _i <= 2; i = ++_i) {
      c = parseInt(hex.substr(i * 2, 2), 16);
      c = Math.round(Math.min(Math.max(0, c + c * lum), 255)).toString(16);
      rgb += ('00' + c).substr(c.length);
    }
    return rgb;
  };

  signature = document.getElementById('signature');

  wololo = new Audio('snd/wololo.mp3');

  signature.onclick = function() {
    var color;
    wololo.play();
    wololo = new Audio('snd/wololo.mp3');
    if (Math.random < 0.05) {
      console.log('goes');
      window.open('https://www.youtube.com/watch?v=dQw4w9WgXcQ', '_blank');
      return;
    }
    color = getRandomColor();
    document.body.style.background = color;
    jss.set('h1, h2, h3, p', {
      color: 'white'
    });
    jss.set('a, .links a', {
      color: ColorLuminance(color, 0.5),
      'text-decoration': 'none'
    });
    return jss.set('a:hover, .links a:hover', {
      color: ColorLuminance(color, 0.7),
      'text-decoration': 'none'
    });
  };

}).call(this);
