# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Install dependencies & run dev environment
    init: gem install bundler jekyll # runs during prebuild
    command: jekyll serve

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 4000
    onOpen: open-preview
