# Site settings
title: David da Silva Contín
email: dasilvacontin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  David da Silva loves designing new experiences and bringing them to life.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dasilvacont.in" # the base hostname & protocol for your site
twitter_username: dasilvacontin
github_username:  dasilvacontin

# Build settings
permalink: /blog/:year/:month/:day/:title
markdown: kramdown
